name: 'rs-fmt-check'
description: 'Run rustfmt and annotate the diff with suggested changes'
author: 'clechasseur'
inputs:
  toolchain:
    description: Toolchain to use (without the `+` sign); defaults to `nightly`
    default: 'nightly'
  args:
    description: Arguments for the cargo fmt command
    required: false
  working-directory:
    description: Directory where to perform cargo fmt command
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: clipboard
  color: black
